CREATE DATABASE IF NOT EXISTS bancoIoT;

USE bancoIoT;

CREATE TABLE Time (
	id INT PRIMARY KEY AUTO_INCREMENT,
	tempo TIMESTAMP NOT NULL;
);
CREATE TABLE Temperatura (
	id INT PRIMARY KEY AUTO_INCREMENT,
	temperatura DOUBLE NOT NULL,
	idTime INT NOT NULL,
	FOREIGN KEY (idTime) REFERENCES Time(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE Agua (
	id INT PRIMARY KEY AUTO_INCREMENT,
	volumeAgua DOUBLE NOT NULL,
	idTime INT NOT NULL,
	FOREIGN KEY (idTime) REFERENCES Time(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE Umidade (
	id INT PRIMARY KEY AUTO_INCREMENT,
	porcentagemAr DOUBLE NOT NULL,
	porcentagemSolo DOUBLE NOT NULL,
	idTime INT NOT NULL,
	FOREIGN KEY (idTime) REFERENCES Time(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);
